version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: powlketbank-db-8083
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: powlketbank_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: